FROM node:20-alpine AS build 
WORKDIR /app


# Copy package files and install dependencies first 
COPY package*.json . 
RUN npm ci 

# Copy source and build the React App 
COPY . . 
RUN npm run build 

# ---- Runtime STage ----
# Serve the built static files with Nginx 
FROM nginx:alpine AS runtime 
COPY --from=build /app/dist /usr/share/nginx/html 
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]